### ISSUE TITLE
Reject self-signed vCenter certificate by default

### ISSUE THREAD

**Issue by mkuzmin** [mkuzmin/terraform-vsphere#13]
add optional `insecure` parameter

**Comment by mkuzmin** [comment]
This change breaks backward compatibility.
If you see `x509: certificate signed by unknown authority` error message, then set 

```
provider "vsphere" {
  insecure_connection = true
}
```

**Comment by KZachariassen** [comment]
This doesn't work for me?

```
Terraform v0.6.12
provider.vsphere: : invalid or unknown key: insecure_connection
```

**Comment by tommymalmqvist** [comment]
it's called `allow_unverified_ssl`now
