### ISSUE TITLE
Being able to set custom attributes to VM

### ISSUE THREAD

**Issue by rogierlommers** [mkuzmin/terraform-vsphere#15]
Not sure if Govmomi supports it, but we would like to be able to set some additional properties. For example, have a look at an example piece of a .vmx file on the ESX host in te /vmfs/volumes directory:

```
/vmfs/volumes/5486bf8c-adb425de-a078-6c3be5bda200/shd-lgc-proxy-001 # grep "machine\.id" shd-lgc-proxy-001.vmx
```

Result:

```
machine.id = "shd-lgc-proxy-001#shddmzams5-rhel64-template#shd-esx-005.bolcom.net"
```

As you can see the key "machine.id" is filled with some value. We use this value for PXE boot purposes. Do you think it's possible for terraform-vsphere to fill up these custom attributes?

**Comment by mkuzmin** [comment]
A new parameter `configuration_parameters` allows specifying custom properties. It's a map, a complete example will look like

```
resource "vsphere_virtual_machine" "params" {
    name =  "base"
    image = "clone"
    configuration_parameters = {
        machine.id = "shd-lgc-proxy-001#shddmzams5-rhel64-template#shd-esx-005.bolcom.net"
       another_parameter = 123
    }
}
```
