### ISSUE TITLE
Support VM customization for Windows guests

### ISSUE THREAD

**Issue by mkuzmin** [mkuzmin/terraform-vsphere#18]
At the moment only Linux guests are supported.

(related issue: #2)

**Comment by opticpow** [comment]
I have done a little work on this here https://github.com/opticpow/terraform-vsphere/tree/customspec
I went the route of using the customisation specification manager as that will support both windows & linux. New to golang, so feel free to checkout before I do a pull request

**Comment by mkuzmin** [comment]
The code looks good. Please feel free to open pull requests - any help and collaboration is very welcome, you don't need to ask for permission :)

I'll test the change more carefully then.

**Comment by gitmayor** [comment]
Hi,
 You guys doing great job. Is there any update on this issue. I tried vSphere plugin with latest TF v0.6.9, against Windows template and it failed on customization with similar error saying: "Specified parameter was not correct.". Any ETA for the fix? Thanks.

**Comment by mkuzmin** [comment]
The plugin is deprecated. No more changes are planned.
