### ISSUE TITLE
Cloning to a different datastore

### ISSUE THREAD

**Issue by mkuzmin** [mkuzmin/terraform-vsphere#21]
When target host does not have access to a datastore where source image is placed, Terraform fails with error like `Unable to access the virtual machine configuration: Unable to access file [vm-Vagrant] ubuntu-SNAPSHOT/ubuntu-SNAPSHOT.vmtx`.

Need to detect target datastore automatically, or specify it explicitly.

**Comment by kc11381** [comment]
Hi,

Do we have the option to specify datastore in tf file?
Thank you.

**Comment by mkuzmin** [comment]
The plugin is deprecated. No more changes are planned.
