### ISSUE TITLE
Provider not providing default Host/IP for provisioner connection block 

### ISSUE THREAD

**Issue by talarczykco** [mkuzmin/terraform-vsphere#22]
I just opened an issue in the main Terraform project that suggests the terrarform-vsphere provider is not providing the default Host/IP when using SSH as the provisioner (at least in my case.)

Here's the other issue: https://github.com/hashicorp/terraform/issues/2237

Am I right in thinking terraform-vsphere should be providing this default value?

**Comment by mkuzmin** [comment]
Thank you for feedback!
I have fixed this in https://github.com/mkuzmin/terraform-vsphere/releases/tag/v0.5

**Comment by talarczykco** [comment]
Looks good - thanks Michael!
