### ISSUE TITLE
* Cannot find resource pool

### ISSUE THREAD

**Issue by redbarron23** [mkuzmin/terraform-vsphere#25]
what do if your ESX Data Centre has no pools
it is clustered but no resource pools

not sure which value to use for resource_pool if no pool exists

thanks

**Comment by mkuzmin** [comment]
It should be supported. Please provide example of problem configuration and command output.

**Comment by redbarron23** [comment]
# config

provider "vsphere" {
  vcenter_server = "tewrvcn1"
  user = "win1\jhourihane"
  password = "xxxxxx"
  insecure_connection = true
}

resource "vsphere_virtual_machine" "gewrdmzwwe3dv" {
  name =  "gewrdmzwwe3dv"
  image = "New OS Templates/CentOS6.5"
  datacenter = "Qwest"
  host = "gewrdmzesx1"
  #resource_pool = "EWR_DMZ_Cluster1"

}

# terraform cmd

[jhourihane@tewradm1 terraform]$  ./terraform apply
vsphere_virtual_machine.gewrdmzwwe3dv: Creating...
  cpus:          "" => "<computed>"
  datacenter:    "" => "Qwest"
  folder:        "" => "<computed>"
  host:          "" => "gewrdmzesx1"
  image:         "" => "New OS Templates/CentOS6.5"
  ip_address:    "" => "<computed>"
  linked_clone:  "" => "0"
  memory:        "" => "<computed>"
  name:          "" => "gewrdmzwwe3dv"
  power_on:      "" => "1"
  resource_pool: "" => "<computed>"
vsphere_virtual_machine.gewrdmzwwe3dv: Error: 1 error(s) occurred:
- Cannot find resource pool
  Error applying plan:

1 error(s) occurred:
- 1 error(s) occurred:
- 1 error(s) occurred:
- Cannot find resource pool

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
[jhourihane@tewradm1 terraform]$

**Comment by mkuzmin** [comment]
Thank you, I've reproduced it now.

Can you specify a name of the cluster instead of specific ESXi server in `host` parameter?

**Comment by redbarron23** [comment]
hmmm.
same outcome
seems like resource_pool is required

[jhourihane@tewradm1 terraform]$ ./terraform plan -out wwe3.out
Refreshing Terraform state prior to plan...

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: wwe3.out
- vsphere_virtual_machine.gewrdmzwwe3dv
  cpus:          "" => "<computed>"
  datacenter:    "" => "Qwest"
  folder:        "" => "<computed>"
  host:          "" => "Qwest"
  image:         "" => "New OS Templates/CentOS6.5"
  ip_address:    "" => "<computed>"
  linked_clone:  "" => "0"
  memory:        "" => "<computed>"
  name:          "" => "gewrdmzwwe3dv"
  power_on:      "" => "1"
  resource_pool: "" => "<computed>"

[jhourihane@tewradm1 terraform]$ ./terraform apply
vsphere_virtual_machine.gewrdmzwwe3dv: Creating...
  cpus:          "" => "<computed>"
  datacenter:    "" => "Qwest"
  folder:        "" => "<computed>"
  host:          "" => "Qwest"
  image:         "" => "New OS Templates/CentOS6.5"
  ip_address:    "" => "<computed>"
  linked_clone:  "" => "0"
  memory:        "" => "<computed>"
  name:          "" => "gewrdmzwwe3dv"
  power_on:      "" => "1"
  resource_pool: "" => "<computed>"
vsphere_virtual_machine.gewrdmzwwe3dv: Error: 1 error(s) occurred:
- Cannot find resource pool
  Error applying plan:

1 error(s) occurred:
- 1 error(s) occurred:

**Comment by redbarron23** [comment]
I found this  
"The cluster itself represents the root resource pool. If you do not create child resource pools, only the root resource pools exist."
http://vmw.re/1HkX9IB
but alas did not work when I used the name of the cluster for the resource pool
I also tried specifying a "fixed" host
however same message

**Comment by mkuzmin** [comment]
Have you found a solution? Could you share it here?

**Comment by redbarron23** [comment]
sorry I didn't and I don't have time at the moment
so I decided to close the issue

**Comment by mattpep** [comment]
I've run into this problem too. Would you prefer me to continue discussion here, or to raise my own issue instead?

**Comment by mkuzmin** [comment]
Let's continue here.

what do you specify in `host` parameter - a name of a clustered compute resorce or a name of specific vSphere (ESXi) node?

**Comment by mattpep** [comment]
I specify a single node (which is in a cluster, currently containing only that one host):

`host = "hv2.<projectname>.local"`

On a point of curiosity, I created a new pool (at the top of the hierarchy, so no parents) and even with

 `resource_pool = "mattp"`

I still get the error:

`* Cannot find resource pool mattp`

(I've removed the resource_pool option again for the purpose of diagnosing this issue)

**Comment by mattpep** [comment]
I've made an interesting discovery: If I specify the cluster name then the node creation succeeds. As best I can tell, the line of likely relevance is https://github.com/mkuzmin/terraform-vsphere/blob/6814028be741262a575b41d8577fadde537d6c62/resource_virtual_machine.go#L187

I don't know VMware well enough to say whether treating a hostname of a host in a cluster as invalid is expected behaviour or not, but if so then this issue can be closed.

**Comment by emdem** [comment]
Ideally, it'd be nice to set the hostname to the host in a cluster, rather than the cluster. What if one has multiple hosts in a cluster and only wants to deploy to one of them without paying for the extra license to be able to create resource pools?

**Comment by kc11381** [comment]
Hi Emdem,

Did you get the thing working. I have exactly the same environment as mentioned by you.
Do we have any update here?

**Comment by prafullwar** [comment]
Did any one got it working I am also facing the same issue.

**Comment by mkuzmin** [comment]
The plugin is deprecated. No more changes are planned.
