### ISSUE TITLE
can not create a simple vm from an image

### ISSUE THREAD

**Issue by ghost** [mkuzmin/terraform-vsphere#26]
Hi,

Here my stack trace from terraform:

---

vsphere_virtual_machine.jenkins: Creating...
  cpus:          "" => "1"
  datacenter:    "" => "<computed>"
  folder:        "" => "<computed>"
  host:          "" => "<computed>"
  image:         "" => "bastion"
  ip_address:    "" => "<computed>"
  linked_clone:  "" => "0"
  memory:        "" => "1"
  name:          "" => "jenkins"
  power_on:      "" => "1"
  resource_pool: "" => "respool1"
vsphere_virtual_machine.jenkins: Error: 1 error(s) occurred:
- Unknown compute resource format of base VM: ha-compute-res
  Error applying plan:

1 error(s) occurred:
- 1 error(s) occurred:
- 1 error(s) occurred:
- Unknown compute resource format of base VM: ha-compute-res

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
## above and apply again to incrementally change your infrastructure.

I use this simple config:

provider "vsphere" {
  vcenter_server = "192.168.31.62:443"
  user = "root"
  password = "redacted"
  insecure_connection = true
}
resource "vsphere_virtual_machine" "jenkins" {
  name =  "jenkins"
  image = "bastion"
  resource_pool = "respool1"
 }

Any idea about this error message?

Thx

**Comment by mkuzmin** [comment]
It looks your vSphere cluster has High Availability option enabled.
It will require a special support from my side. I will be able to look into this in about two weeks, after my vacation. sorry.

**Comment by ghost** [comment]
How to desactivate it ?

Thx

**Comment by mkuzmin** [comment]
If your vSphere datacenter has another hosts, where HA option is disabled, please try to use them

**Comment by ghost** [comment]
No HA other host

Just one single host

**Comment by mkuzmin** [comment]
The plugin is deprecated. No more changes are planned.
