### ISSUE TITLE
 A specified parameter was not correct. spec.identity

### ISSUE THREAD

**Issue by cignul9** [mkuzmin/terraform-vsphere#27]
Terraform creates the machine all the way to the ethernet interface correctly, but doesn't poweron the box and instead fails with the error in the title.  I'm not sure what I'm doing wrong.  The template I'm cloning from is Windows.  There doesn't seem to be any log beyond this generic message.  What can I do to troubleshoot this.  Here's my terraform.tf:

provider "vsphere" {
  user = "<redacted>"
  password = "<redacted>"
  vcenter_server = "<redacted>"
}
resource "vsphere_virtual_machine" "inttstsqlv04" {
  name = "inttstsqlv04"
  domain = "nt.local"
  time_zone = "America/Denver"
  datacenter = "DC AF"
  cluster = "BL460V2"
  vcpu = 2
  memory = 4096
  disk {
    datastore = "VNXLun122_R6NLSAS"
    template = "TEMPLATES/Windows Server 2012 R2 Terraform Template"
  }
  network_interface {
    label = "BO 10.122.12.x"
    ip_address = "10.122.12.42"
    subnet_mask = "255.255.255.0"
  }
}

**Comment by mkuzmin** [comment]
Right now customization of Windows machines is not supported, as they require more mandatory parameters in VM customization specifications.

Good news is the plugin will support external customization specs soon.

There is issue #18 talking about the same problem. I'm going to close this one, but feel free to comment  there.

**Comment by gitmayor** [comment]
Hi,
You guys doing great job. Is there any update on this issue. I tried vSphere plugin with latest TF v0.6.9, against Windows template and it failed on customization with similar error saying: "Specified parameter was not correct.". Any ETA for the fix? Thanks.
