### ISSUE TITLE
Enhancement request : support for ESXi host and disk parameters

### ISSUE THREAD

**Issue by kc11381** [mkuzmin/terraform-vsphere#28]
Hi,

I want to modify "terraform-provider-vsphere" provider to include 2 more fields while creating vms.
1. Based on some ratio of vCPU available on ESXi servers on VCenter.
2. Attaching disk based on "x" capacity availability.

These 2 parameters will be calculated at run time.(may be when we say terraform plan/ apply)

Please suggest the pointers for the same.
Thank you.

**Comment by kc11381** [comment]
Hi,

Please update here.
Thank you.

**Comment by mkuzmin** [comment]
The plugin is deprecated. No more changes are planned.
