### ISSUE TITLE
Difference between this and the plugin included with terraform ?

### ISSUE THREAD

**Issue by erSitzt** [mkuzmin/terraform-vsphere#30]
Hi,

is your plugin the base for the one shipped with terraform or are they different ?

regards

**Comment by chrislovecnm** [comment]
@erSizt there are various community providers and the one in terraform was added about a month ago, from another community version.

They are different. The one built in to terraform is new to terraform, but not new code.

**Comment by erSitzt** [comment]
Ok thanks for the info !
